version: '3.1'

services:

  mongo:
    image: mongo:4.4.5
    restart: always
    container_name: car_bot_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - .docker/mongo/data:/data/db
      - .docker/mongo/config/setup.sh:/docker-entrypoint-initdb.d/create_mongo_users.sh
    command: mongod --auth
    ports:
      - 27018:27017